config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'privacy', to: 'static_pages#privacy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'
  get 'landing', to: 'static_pages#landing'

  devise_for :admins, controllers: { sessions: "admins/sessions"}

  devise_scope :admin do
    get "sign_out", to: "admins/sessions#destroy"
  end

  resources :posts, controller: 'posts/posts', except: :index, path: ""

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #:registerable, :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable,:rememberable
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug, use: :slugged

  default_scope -> { order('id DESC') }

  belongs_to :admin

  before_save :should_generate_new_friendly_id?, if: :slug_changed?

  private

    def should_generate_new_friendly_id?
      slug_changed?
    end

end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    redirect_to root_url
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:display_name, :email, :password, :password_confirmation) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:display_name, :email, :password, :password_confirmation, :current_password) }
    end

end

app/controllers/posts/posts_controller.rb
class Posts::PostsController < ApplicationController

  before_action :authenticate_admin!, except: [:index, :show]

  def show
    @post = Post.friendly.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.admin_id = current_admin.id
    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id]).destroy
    redirect_to root_url
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :slug, :image)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @posts = Post.all
  end

  def privacy
  end

  def terms_of_use
  end

  def contact
  end

  def about
  end

  def landing
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Psych Born"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'partials/shim' %>
  <%= render 'partials/statcounter' %>
</head>
<body>

<%= yield %>

<%= render 'partials/footer' %>

</body>
</html>

app/views/partials/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to 'psych born', root_url %></li> |
      <li><%= link_to 'privacy', privacy_path %></li> |
      <li><%= link_to 'terms of use', terms_of_use_path %></li> |
    </ul>
  </nav>
</footer>

app/views/partials/_header.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to 'home', root_url %></li>
      <li><%= link_to 'about', about_path %></li>
      <li><%= link_to 'contact', contact_path %></li>
      <li><%= link_to 'free updates', landing_path %></li>
    </ul>
  </nav>
  <h1>
    psych born
  </h1>
</header>

app/views/partials/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
</script>
<![endif]-->

app/views/partials/_statcounter.html.erb
<script type="text/javascript">
var sc_project=8830776;
var sc_invisible=1;
var sc_security="808bc352";
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter.js'></"+"script>");
</script>
<noscript><div class="statcounter"><a title="web stats"
href="http://statcounter.com/free-web-stats/"
target="_blank"><img class="statcounter"
src="http://c.statcounter.com/8830776/0/808bc352/1/"
alt="web stats"></a></div></noscript>

app/views/posts/posts/edit.html.erb
<%= provide(:title,  "Edit " + sanitize(@post.title)) %>

<%= render 'partials/header' %>

<main>

  <h2>Edit <%= @post.title %></h2>

  <%= form_for(@post, url: post_path) do |f| %>
    <div>
      <%= f.text_field :title, placeholder: "title" %>
    </div>
    <div>
      <%= f.text_field :slug, placeholder: "slug" %>
    </div>
    <div>
      <%= f.text_field :image, placeholder: "image" %>
    </div>
    <div>
      <%= f.text_area :content, placeholder: "content" %>
    </div>
    <div>
      <%= f.submit "edit post" %>
    </div>
  <% end %>

</main>

app/views/posts/posts/new.html.erb
<%= provide(:title,  "New Post") %>

<%= render 'partials/header' %>

<main>

  <h2>New Post</h2>

  <%= form_for(@post, url: posts_path) do |f| %>
    <div>
      <%= f.text_field :title, placeholder: "title" %>
    </div>
    <div>
      <%= f.text_field :slug, placeholder: "slug" %>
    </div>
    <div>
      <%= f.text_field :image, placeholder: "image" %>
    </div>
    <div>
      <%= f.text_area :content, placeholder: "content" %>
    </div>
    <div>
      <%= f.submit "publish post" %>
    </div>
  <% end %>

</main>

app/views/posts/posts/show.html.erb
<%= provide(:title,  sanitize(@post.title)) %>

<%= render 'partials/header' %>

<main>
  <h2>
    <%=@post.title %>
  </h2>
  <img srcset="<%= @post.image %>" width="100%" height="auto" />
  <span>By Alex Heil. Follow him on Twitter <a href="https://twitter.com/realalexheil">here</a>. <%= link_to "Hello, Alex.", post_path, data: { confirm: "Care for some Mighty Taco?" }, method: :delete if admin_signed_in? %></span>
  <article>
    <%= sanitize(@post.content) %>
  </article>
  <nav>
    <h3>Share this on...?</h3>
    <ul>
      <li>
        <a href="https://twitter.com/share" class="twitter-share-button" >Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </li>
    </ul>
  </nav>
  <nav>
    <ul>
    <% if Post.exists?(@post.id + 1) %>
        <li>< Next - <%= link_to "#{Post.find(@post.id + 1).title}", post_path(Post.find(@post.id + 1)) %></li>
      <% else %>
      <% end %>
      <% if Post.exists?(@post.id - 1) %>
        <li><%= link_to "#{Post.find(@post.id - 1).title}", post_path(Post.find(@post.id - 1)) %> -  Previous ></li>
      <% else %>
      <% end %>
    </ul>
  </nav>
</main>

app/views/static_pages/about.html.erb
<%= provide(:title,  "About") %>

<header>
  <h1><%= link_to "psych born", root_url %></h1>
</header>

<main>
  <h2>
    About Alex Heil and Psych Born
  </h2>
  <article>
    I'm Alex Heil, psychology student at the University of Buffalo. I've written over 400 articles in the self-help niche via developyourlife.net (the old one, not that new one), but am now focusing deeper on helping improve life with psychology hacks.

    I have learned a lot about psychology in the past few years while working on my old blogs, and I’m ready to pour my knowledge into a golden goblet and have you take a swig out of it.

    Psychology is not an easy field, what with all the brain stuff and all, which is why I want to make this website simple to read and understand. That way no matter what your education level, you’ll get something out of this.

    Using all my knowledge in the psychology field, and I’m still learning (I still can’t spell psychology without looking it up in the dictionary every time), I know I can produce great, useful content that will make your life better.

    Oh, and maybe you’ve noticed that this blog is pretty simple looking. That’s because you’re here to learn, not be plastered with hundreds of megabytes worth of ads (I’m looking at your Forbes) and it’s going to stay like that forever. Occasionally, I may recommend a product, such as a book, in which I may make money from through affiliate sales. Hey, that Ramen isn’t going to afford itself.

    <div>Follow me on Twitter - <a href="https://twitter.com/RealAlexHeil">@RealAlexHeil</a>.
  </article>
</main>

app/views/static_pages/contact.html.erb
<%= provide(:title,  "Contact") %>

<header>
  <h1><%= link_to "psych born", root_url %></h1>
</header>

<main>
  <h2>
    Contact
  </h2>
  <article>
    Forms are useless. Contact me on Twitter <a href="https://twitter.com/RealAlexHeil">@RealAlexHeil</a>.
  </article>
</main>

app/views/static_pages/home.html.erb
<%= render 'partials/header' %>

<main>
  <% if @posts.any? %>
    <% @posts.each do |post| %>
    <h2>
      <%= link_to post.title, post_path(post) %>
    </h2>
    <img srcset="<%= post.image %>" width="100%" height="auto" />
    <span>By Alex Heil. Follow him on Twitter <a href="https://twitter.com/realalexheil">here</a>.</span>
    <article>
      <%= raw(post.content).split("<h3>").first %>
      <%= link_to "Read more...", post_path(post) %>
    </article>
    <% end %>
  <% else %>
    There are no posts on the site. Go home now.
  <% end %>
</main>

app/views/static_pages/landing.html.erb
<%= provide(:title,  "Free Updates") %>

<header>
  <h1><%= link_to "psych born", root_url %></h1>
</header>

<main>
  <h2>
    How You Can Use Proven Psychological Methods to Increase Your Happiness, Better Your Memory, and Improve Your Life
  </h2>
  <article>
    Sign up to the Psych Born newsletter for free and you’ll learn how you can use psychology to “get smart” about your life…

    …And then you’ll see why it’s absolutely VITAL that you take advantage of these methods.

    You also gain access to my FREE eBook titled, : ) The REAL Key to the Pursuit of Happiness.

    Guess what?! Those few sentences above this one are old! They don't apply at the moment.

    Why don't I just delete them?

    Good question.

    Because they soon will apply. Once I get more readers on the site.

    <h3>Want free updates?</h3>

    You can do two things:

    First. Follow me on Twitter <a href="https://twitter.com/RealAlexHeil">@RealAlexHeil</a>.

    Share this site with your friends! Once I get 1,000 or so unique visitors per day I'll reopen my email newsletters.

    Until then...
  </article>
</main>

app/views/static_pages/privacy.html.erb
<%= provide(:title,  "Privacy Policy") %>

<header>
  <h1><%= link_to "psych born", root_url %></h1>
</header>

<main>
  <h2>
    Privacy Policy
  </h2>
  <article>
    <strong>Effective Date:</strong> <i>February 16th, 2013</i>

    The following Privacy Policy governs the online information collection practices of PSYCH BORN (“we” or “us”). Specifically, it outlines the types of information that we gather about you while you are using the PsychBorn.com website (the “Site”), and the ways in which we use this information. This Privacy Policy, including our children’s privacy statement, does not apply to any information you may provide to us or that we may collect offline and/or through other means (for example, at a live event, via telephone, or through the mail).

    Please read this Privacy Policy carefully. By visiting and using the Site, you agree that your use of our Site, and any dispute over privacy, is governed by this Privacy Policy. Because the Web is an evolving medium, we may need to change our Privacy Policy at some point in the future, in which case we’ll post the changes to this Privacy Policy on this website and update the Effective Date of the policy to reflect the date of the changes. By continuing to use the Site after we post any such changes, you accept the Privacy Policy as modified.

    PyschBorn.com strives to offer its visitors the many advantages of Internet technology and to provide an interactive and personalized experience. We may use Personally Identifiable Information (your name, e-mail address, street address, telephone number) subject to the terms of this privacy policy. We will never sell, barter, or rent your email address to any unauthorized third party.

    <h3>We collect but do not link personal and activity data.</h3>

    We use technologies like cookies (small files stored by your browser), web beacons, or unique device identifiers to anonymously identify your computer or device so we can deliver a better experience. Our systems also log information like your browser, operating system and IP address.

    We also may collect personally identifiable information that you provide to us, such as your name, address, phone number or email address. With your permission, we may also access other personal information on your device, such as your phone book, calendar or messages, in order to provide services to you. If authorized by you, we may also access profile and other information from services like Facebook.

    Our systems are not designed to associate personal information with your activities (such as pages you view or things you click on or search for).

    We do not knowingly contact or collect personal information from children under 13. If you believe we have inadvertently collected such information, please contact us so we can promptly obtain parental consent or remove the information.

    <h3>We may collect but do not share your location history.</h3>

    To customize our service for you, we may collect and store your precise geographic location as part of your user profile. This data generally is not shared with others. We may ask for your consent on your first use of the service.

    <h3>You can request to see or delete your personal data.</h3>

    You can sign into your account to see or delete any personally identifiable information we have stored, such as your name, address, email or phone number. You can also contact us by email to request to see or delete this information.

    <h3>We keep personal data until you delete it.</h3>

    We remove personally identifiable information (such as your name, address, email or phone number) and other preferences associated with your account promptly after you delete your account. We may retain other data indefinitely.

    <h3>We don’t share your personal information with marketers.</h3>

    We generally do not share personally identifiable information (such as name, address, email or phone) with other companies for marketing purposes.

    <h3>No ad companies collect data through our service.</h3>

    We do not allow advertising companies to collect data through our service for ad targeting.

    <h3>Service providers access data on our behalf.</h3>

    In order to serve you, we may share your personal and anonymous information with other companies, including vendors and contractors. Their use of information is limited to these purposes, and subject to agreements that require them to keep the information confidential. Our vendors provide assurance that they take reasonable steps to safeguard the data they hold on our behalf, although data security cannot be guaranteed.

    Analytics companies may access anonymous data (such as your IP address or device ID) to help us understand how our services are used. They use this data solely on our behalf. They do not share it except in aggregate form; no data is shared as to any individual user. Click to see company privacy policies that govern their use of data.

    <h3>We take steps to protect personal information.</h3>

    We take reasonable steps to secure your personally identifiable information against unauthorized access or disclosure. We encrypt transmission of data on pages where you provide payment information. However, no security or encryption method can be guaranteed to protect information from hackers or human error.

    Information we collect may be stored or processed on computers located in any country where we do business.

    <h3>Special situations may require disclosure of your data.</h3>

    To operate the service, we also may make identifiable and anonymous information available to third parties in these limited circumstances: (1) with your express consent, (2) when we have a good faith belief it is required by law, (3) when we have a good faith belief it is necessary to protect our rights or property, or (4) to any successor or purchaser in a merger, acquisition, liquidation, dissolution or sale of assets. Your consent will not be required for disclosure in these cases, but we will attempt to notify you, to the extent permitted by law to do so.

    <h3>You can ask privacy questions.</h3>

    If you have any questions or concerns about our privacy policies, please contact us:
    Contact Form OR alexheil (at) psychborn.com OR 12068 Million Dollar Hwy, Medina New York, 14103, United States of America

    <h3>Children’s Privacy Policy</h3>

    This children’s privacy statement explains our practices with respect to the online collection and use of personal information from children under the age of thirteen, and provides important information regarding their rights under federal law with respect to such information.

    This Site is not directed to children under the age of thirteen and we do NOT knowingly collect personally identifiable information from children under the age of thirteen as part of the Site. We screen users who wish to provide personal information in order to prevent users under the age of thirteen from providing such information. If we become aware that we have inadvertently received personally identifiable information from a user under the age of thirteen as part of the Site, we will delete such information from our records. If we change our practices in the future, we will obtain prior, verifiable parental consent before collecting any personally identifiable information from children under the age of thirteen as part of the Site.

    Because we do not collect any personally identifiable information from children under the age of thirteen as part of the Site, we also do NOT knowingly distribute such information to third parties.

    We do NOT knowingly allow children under the age of thirteen to publicly post or otherwise distribute personally identifiable contact information through the Site.

    Because we do not collect any personally identifiable information from children under the age of thirteen as part of the Site, we do NOT condition the participation of a child under thirteen in the Site’s online activities on providing personally identifiable information.

    <h3>Changes to this Policy</h3>

    This privacy policy was last updated on February 16th, 2013. Our privacy policy may change from time to time. Please check this page periodically for changes. Your continued use of our site following the posting of changes to these terms will mean you accept those changes. Information collected prior to the time any change is posted will be used according to the rules and laws that applied at the time the information was collected.

    <h3>Governing Law</h3>

    This policy and the use of these Sites are governed by the State of New York law. If a dispute arises under this Policy we agree to first try to resolve it with the help of a mutually agreed-upon mediator in the following location: State of New York. Any costs and fees other than attorney fees associated with the mediation will be shared equally by each of us.

    If it proves impossible to arrive at a mutually satisfactory solution through mediation, we agree to submit the dispute to binding arbitration at the following location: State of New York, under the rules of the American Arbitration Association. Judgment upon the award rendered by the arbitration may be entered in any court with jurisdiction to do so.

    PsychBorn.com is controlled, operated and administered entirely within State of New York. This statement and the policies outlined herein are not intended to and do not create any contractual or other legal rights in or on behalf of any party.
  </article>
</main>

app/views/static_pages/terms_of_use.html.erb
<%= provide(:title,  "Terms of Use") %>

<header>
  <h1><%= link_to "psych born", root_url %></h1>
</header>

<main>
  <h2>
    Terms of Use
  </h2>
  <article>
    Please use the site responsibly.

    <h3>At the moment...</h3>

    There are no services on this site, therefore there is nothing to purchase, meaning no payments will be taken, thus no refunds are available.

    You don’t post any content on my site, so you do not have any proprietary rights to anything on this site, and do not have to follow any sort of content creation code of conduct.

    Please read the <%= link_to "privacy policy", privacy_path %>.

    I will and can change this Terms of Service whenever I want to.

    If you think that I have violated your copyright in any way, tweet me <a href="https://twitter.com/RealAlexHeil">@RealAlexHeil</a>. We will discuss from there.

    This site links to external sites and I am not responsible for what you do on those sites. Oh, and it’s possible it may be an affiliate link. If that’s the case I may make money through affiliate sales.

    That’s it.
  </article>
</main>